stages:
  - dev
  - stag
  - analyze

deploy_dev:
  only:
    - develop
  tags:
    - merapi
  stage: dev
  image: javanlabs/ssh-client:latest
  environment:
    name: onic-fe
    url: https://onic-fe.merapi.javan.id
  script:
    - echo "Deploy ke server merapi"
    - ssh root@192.168.88.210 "cd /opt/alurkerja/onic/onic-fe && sh k8s_update.sh onic-fe"

deploy_stag:
  only:
    - develop
  tags:
    - merapi
  stage: stag
  image: javanlabs/ssh-client:latest
  environment:
    name: onic-fe
    url: https://onic-fe-stag.merapi.javan.id
  script:
    - echo "Deploy ke server merapi"
    - ssh root@192.168.88.210 "cd /opt/alurkerja/onic/onic-fe-stag && sh k8s_update.sh onic-fe-stag"
  when: manual

sonarqube-check:
  tags:
    - merapi
  only:
    - develop
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey=bubur-onic-fe
      -Dsonar.sources=src
      -Dsonar.host.url=https://sonar.javan.co.id
      -Dsonar.login=${SONAR_LOGIN_TOKEN}
  when: manual
